# Generated by Django 3.2.4 on 2021-06-30 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('nip', models.CharField(max_length=255)),
                ('ttl', models.CharField(max_length=255)),
                ('marriage_status', models.CharField(max_length=255)),
                ('religion', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('educationSMA', models.CharField(max_length=255)),
                ('educationD3', models.CharField(max_length=255)),
                ('educationS1', models.CharField(max_length=255)),
                ('educationS2', models.CharField(max_length=255)),
                ('educationS3', models.CharField(max_length=255)),
                ('title1', models.CharField(max_length=255)),
                ('title2', models.CharField(max_length=255)),
                ('title3', models.CharField(max_length=255)),
                ('history1', models.CharField(max_length=255)),
                ('history2', models.CharField(max_length=255)),
                ('history3', models.CharField(max_length=255)),
                ('achievement1', models.CharField(max_length=255)),
                ('achievement2', models.CharField(max_length=255)),
                ('achievement3', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('answers', models.ManyToManyField(to='potensiku.Answer')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='potensiku.person')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='potensiku.question'),
        ),
    ]
