# Generated by Django 3.2.4 on 2021-07-06 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('potensiku', '0003_token_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
