# Generated by Django 3.2.4 on 2022-07-27 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potensiku', '0004_token_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='achievement1',
        ),
        migrations.RemoveField(
            model_name='person',
            name='achievement2',
        ),
        migrations.RemoveField(
            model_name='person',
            name='achievement3',
        ),
        migrations.RemoveField(
            model_name='person',
            name='title1',
        ),
        migrations.RemoveField(
            model_name='person',
            name='title2',
        ),
        migrations.RemoveField(
            model_name='person',
            name='title3',
        ),
    ]
